function createfigure(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 13-Nov-2014 14:45:03

% Create figure
figure1 = figure;
colormap('gray');

% Create axes
axes1 = axes('Parent',figure1,'FontSize',16,'FontName','Adobe Song Std',...
    'Position',[0.13 0.11 0.779470752089136 0.815000000000002]);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('Classification Rate','FontSize',17.6);

% Create xlabel
xlabel('Number of Neurons in One Hidden Layer','FontSize',17.6);

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','traingd');
set(plot1(2),'DisplayName','traingda');
set(plot1(3),'DisplayName','traingdm');
set(plot1(4),'DisplayName','trainrp');
set(plot1(5),'DisplayName','trainscg');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.782746876283892 0.309524035372274 0.114137843053846 0.139662956497646],...
    'FontSize',11);

